### ISSUE TITLE
using LOGZIO token

### ISSUE THREAD

**Issue by owenrumney** [logzio/logzio_terraform_provider#40]
Hey @jonboydell  

When running the TEST_ACC=true to test my PR and I need to supply the `LOGZIO_AUTH_TOKEN`, what is the impact for my logzio install? Is it just going to run a plan or actually try to create something then destroy?

**Comment by jonboydell** [comment]
Good question - in the terraform provider running the tests does the end to end journey for all of them, you can specify which tests you want to run as part of the test command (can't remember the syntax) - however, this highlights a problem with the terraform provider - you should be able to switch between end to end tests and unit tests so that you can choose whether logz.io objects are created or not.  The logz.io client library does have this feature in it and the provider should too.

**Comment by owenrumney** [comment]
Great thanks. I've managed to test the new code that does DiffSupression on JSON filter for alerts. I'm going to run it in with our fork and test it out properly then will raise a PR. Ta
